server:
  port: 8089
spring:
  application:
    name: admin_test    # 项目名称尽量用小写
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://rm-8vb9q0m9d1vtweyguzo.mysql.zhangbei.rds.aliyuncs.com:3306/bht-test?characterEncoding=utf-8&useSSL=false&useCursorFetch=true
        url: jdbc:mysql://rm-8vb9q0m9d1vtweygu.mysql.zhangbei.rds.aliyuncs.com:3306/bht-test?characterEncoding=utf-8&useSSL=false&useCursorFetch=true
      username: bht
      password: bht_2018

mybatis:
  typeAliasesPackage: com.flc.coinmarket.dao.mysql.model.*
  mapperLocations: classpath:mapper/*/*.xml  #指定*Mapper.xml的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

bugumongo:
  db:
    host: 127.0.0.1
    port: 27017
    database: admin


logging:
  level:
    root: INFO
  file: ./logs/admin.log