server:
  port: 8090
spring:
  application:
    name: admin    # 项目名称尽量用小写
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://rm-8vb9q0m9d1vtweygu.mysql.zhangbei.rds.aliyuncs.com:3306/bht?characterEncoding=utf-8&useSSL=false&useCursorFetch=true
      username: bht
      password: bht_2018

mybatis:
  typeAliasesPackage: com.flc.coinmarket.dao.mysql.model.*
  mapperLocations: classpath:mapper/*/*.xml  #指定*Mapper.xml的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

 # //mongodb://root:****@dds-8vbce58e780028c41.mongodb.zhangbei.rds.aliyuncs.com:3717,dds-8vbce58e780028c42.mongodb.zhangbei.rds.aliyuncs.com:3717/admin?replicaSet=mgset-500025988
bugumongo:
  db:
    host: 192.168.0.172
    port: 3717
    database: admin
    username: root
    password: bht_2018

logging:
  level:
    root: INFO
  file: ./logs/admin.log